"""empty message

Revision ID: 0c31c031787f
Revises: 
Create Date: 2020-09-08 12:03:10.242497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c31c031787f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblfilenumber',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_problem', sa.Integer(), nullable=False),
    sa.Column('filenumber', sa.String(length=100), nullable=True),
    sa.Column('filetitle', sa.String(length=100), nullable=True),
    sa.Column('recordtime', sa.DateTime(), nullable=True),
    sa.Column('sync', sa.Integer(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbllabel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(length=1000), nullable=False),
    sa.Column('labelcount', sa.Integer(), nullable=False),
    sa.Column('lastusedtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbllearnnote',
    sa.Column('id_problem', sa.Integer(), nullable=False),
    sa.Column('d_level', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=100), nullable=True),
    sa.Column('answer', sa.String(length=100), nullable=True),
    sa.Column('usedtime', sa.DateTime(), nullable=True),
    sa.Column('usedtimes', sa.Integer(), nullable=False),
    sa.Column('inputdate', sa.DateTime(), nullable=True),
    sa.Column('sync', sa.Integer(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_problem')
    )
    op.create_table('tblpicture',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_problem', sa.Integer(), nullable=True),
    sa.Column('filepath', sa.String(length=100), nullable=True),
    sa.Column('isanswer', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_problem'], ['tbllearnnote.id_problem'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblpicture')
    op.drop_table('tbllearnnote')
    op.drop_table('tbllabel')
    op.drop_table('tblfilenumber')
    # ### end Alembic commands ###
